name: briefcase
description: An experimental peer-to-peer network.
version: 0.0.1
# homepage: https://briefcase.network/

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  pubspec_extract: ^2.0.2
  messagepack: ^0.2.1

dev_dependencies:
  build_runner: ^2.1.5
  lints: ^1.0.0
